const assert=require('node:assert/strict');
const fs=require('node:fs');
module.exports=async(cdp,evaluate)=>{
 const results=await evaluate(`(async()=>{
  const checks=[];const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};const q=s=>ui.shadow.querySelector(s);const click=s=>{const e=q(s);if(!e)throw Error('Missing '+s);e.click();};const pause=ms=>new Promise(r=>setTimeout(r,ms));
  Object.assign(window.SillyTavern,{POPUP_TYPE:{CONFIRM:2,INPUT:1},POPUP_RESULT:{AFFIRMATIVE:1,CANCELLED:0}});
  ui.state.activeTab='summary';ui.render();await pause(100);
  check('总结作为第六导航体系中的独立页面',!!q('.summary-slot .sa-panel')&&q('.sa-tabs').textContent.includes('记录')&&q('.sa-tabs').textContent.includes('生成设置'));
  check('新装默认关闭总结',!q('#sa-enabled').checked&&!ui.summary.capture().enabled);
  click('#sa-enabled');await pause(30);check('总结启用开关独立持久化',vars.summary_assistant_settings.enabled===true);
  click('[data-tab="settings"].sa-tab-item');
  q('#sa-trigger-count').value='41';q('#sa-trigger-count').dispatchEvent(new Event('input',{bubbles:true}));
  await pause(850);check('总结参数自动保存',ui.summary.capture().triggerFloorCount===41);
  await ui.setGlobalPreference('保存预设不丢总结');await ui.settle();check('预设整表保存不覆盖总结',vars.summary_assistant_settings.triggerFloorCount===41);
  click('[data-tab="prompts"].sa-tab-item');
  click('[data-block-edit]');await pause(20);
  const text=q('[data-form-field="content"]');text.value='保存后的提示词草稿';
  ui.renderActiveContent(true);check('同步刷新保留条目编辑弹窗草稿',q('[data-form-field="content"]').value==='保存后的提示词草稿');
  click('.dj-dialog-actions button');await pause(900);
  click('.tabs [data-tab="daily"]');await pause(50);click('.tabs [data-tab="summary"]');await pause(50);
  check('切换页面保留总结子页与已编辑条目',q('.sa-tab-item.active').dataset.tab==='prompts'&&ui.summary.capture().promptBlocks[0].content==='保存后的提示词草稿');
  const before=ui.summary.capture().promptBlocks.length;
  click('[data-action-add-block]');await pause(20);
  check('新增提示词使用统一主题弹窗',!!q('.dj-dialog')&&!document.querySelector('.sa-overlay'));
  q('.dj-dialog textarea').value='自建总结规则';q('.dj-dialog-actions button').click();await pause(900);
  check('新增提示词自动保存',ui.summary.capture().promptBlocks.length===before+1);
  const added=ui.summary.capture().promptBlocks.at(-1);check('新增提示词名称保存',added.name==='自建总结规则');
  q('[data-block-edit="'+added.id+'"]').click();await pause(30);click('.dj-dialog-actions button:nth-child(2)');await pause(30);click('.dj-dialog-actions button');await pause(900);check('删除提示词自动保存',ui.summary.capture().promptBlocks.length===before);
  await ui.summary.flush();
  click('.tabs [data-tab="configurations"]');
  q('[data-action="configuration-scope"][data-kind="save"][data-key="preset"]').click();
  q('[data-action="configuration-name"]').value='仅总结';q('[data-action="configuration-name"]').dispatchEvent(new Event('input',{bubbles:true}));
  click('[data-action="configuration-save-new"]');await ui.settle();
  const item=ui.configLibrary().items.find(i=>i.name==='仅总结');check('保存范围勾选生成仅总结配置',item?.snapshot.summary&&!item.snapshot.preset);
  const original=JSON.stringify(data);await ui.summary.apply({...ui.summary.capture(),triggerFloorCount:61});await ui.applyConfiguration(item.id);
  check('仅总结配置切换不改动预设',JSON.stringify(data)===original&&ui.summary.capture().triggerFloorCount===41);
  check('恢复点只记录受影响的总结部分',!!ui.configLibrary().recovery.snapshot.summary&&!ui.configLibrary().recovery.snapshot.preset);
  await ui.applyConfiguration('__recovery__');check('仅总结恢复点还原总结参数',ui.summary.capture().triggerFloorCount===61&&JSON.stringify(data)===original);
  const both=await ui.saveNamedConfiguration('两类配置','',{preset:true,summary:true});
  const exported=JSON.parse(ui.exportConfigurations(both,{preset:false,summary:true}));check('导出可再次筛选范围',exported.version===2&&exported.items[0].snapshot.summary&&!exported.items[0].snapshot.preset);
  const legacy={format:'destined-configurations',version:1,items:[{id:'old-config',name:'旧版配置',snapshot:ui.captureConfiguration()}]};await ui.importConfigurations(JSON.stringify(legacy));
  const old=ui.configLibrary().items.find(i=>i.id==='old-config');check('旧版配置导入为仅预设',old.snapshot.preset&&!old.snapshot.summary);
  const exp=ui.exportConfigurations();check('配置导出不含密钥、世界书和记录',!exp.includes('customApiKey')&&!exp.includes('summary_assistant_worldbook')&&!exp.includes('summary_assistant_mega_summary_map'));
  let failed=false;try{ui.exportConfigurations('',{preset:false,summary:false})}catch{failed=true}check('导出不允许空范围',failed);
  // Exercise actual summary action, review and worldbook save through the UI.
  window.books={};window.chatVars={};window.globalBooks=[];window.messages=Array.from({length:30},(_,id)=>({message_id:id,role:'assistant',message:'<tp>488-1-1</tp><gametxt>发生事件'+id+'</gametxt>',is_hidden:false}));
  window.getVariables=o=>structuredClone(o?.type==='chat'?chatVars:vars);
  window.replaceVariables=(value,o)=>{if(o.type==='chat')chatVars=structuredClone(value);else vars=structuredClone(value);};
  window.insertOrAssignVariables=(value,o)=>{const next=mergeTavernVariables(getVariables(o),value);replaceVariables(next,o);return next;};
  window.getWorldbookNames=async()=>Object.keys(books);window.getWorldbook=async n=>structuredClone(books[n]||[]);
  window.getGlobalWorldbookNames=()=>globalBooks;window.rebindGlobalWorldbooks=async n=>{globalBooks=n};
  window.createWorldbook=async(n,v)=>{books[n]=structuredClone(v)};window.createWorldbookEntries=async(n,v)=>books[n].push(...structuredClone(v));window.updateWorldbookWith=async(n,fn)=>{books[n]=await fn(structuredClone(books[n]))};
  window.getLastMessageId=()=>messages.length-1;
  window.getChatMessages=(range,o={})=>{const [a,b]=range.split('-').map(Number);return structuredClone(messages.filter(m=>m.message_id>=a&&m.message_id<=b&&(o.hide_state!=='hidden'||m.is_hidden)))};
  window.setChatMessages=async values=>values.forEach(v=>Object.assign(messages[v.message_id],v));
  window.SillyTavern={getContext:()=>({chatId:'assistant-test',characterId:1}),name1:'用户',name2:'角色',POPUP_TYPE:{CONFIRM:2,INPUT:1},POPUP_RESULT:{AFFIRMATIVE:1,CANCELLED:0}};
  window.summaryCalls=0;window.stopIds=[];window.stopGenerationById=id=>stopIds.push(id);
  window.generateRaw=request=>{window.lastRequest=request;summaryCalls++;return new Promise(resolve=>window.finishSummary=resolve);};
  await ui.summary.apply({...ui.summary.capture(),triggerFloorCount:30,enabled:true,promptBlocks:ui.summary.capture().promptBlocks.map(block=>({...block,enabled:block.choiceGroup==='format'?block.id==='format_free':block.enabled}))});ui.state.activeTab='summary';ui.render();await pause(40);
  click('#sa-start-summary');await pause(80);
  check('手动总结后台运行且不弹出确认或审查',!q('.dj-dialog')&&!!q('.sa-notice')&&q('[data-task-title]').textContent.includes('请求生成'));
  check('任务中生成、记录写入与自动隐藏开关禁用',q('#sa-start-summary').disabled&&q('#sa-start-custom-summary').disabled&&q('#sa-reset').disabled&&q('#sa-bind-worldbook').disabled&&q('#sa-vis-auto-hide').disabled);
  q('#sa-start-summary').click();check('连续点击不产生重复请求',summaryCalls===1);
  ui.closePanel();await pause(30);
  const rp=document.createElement('textarea');rp.id='rp-input';document.body.append(rp);rp.focus();rp.value='继续 RP';
  const chatScroll=document.createElement('div');chatScroll.style.cssText='height:100px;overflow:auto';chatScroll.innerHTML='<div style="height:1000px">聊天原文</div>';document.body.append(chatScroll);chatScroll.scrollTop=300;
  await pause(1100);
  check('关闭面板后任务继续且顶部提示不抢焦点滚动',summaryCalls===1&&document.activeElement===rp&&chatScroll.scrollTop===300&&getComputedStyle(q('.sa-notice-layer')).pointerEvents==='none'&&getComputedStyle(q('.sa-notice')).pointerEvents==='auto');
  click('.sa-notice-close');await pause(30);check('关闭提示不会停止生成',q('.sa-notice-layer').hidden&&stopIds.length===0);
  ui.openPanel();await pause(40);click('[data-tab="prompts"].sa-tab-item');
  click('[data-block-edit]');await pause(20);q('[data-form-field="content"]').value='下一次使用的规则';click('.dj-dialog-actions button');await pause(900);
  check('生成期间可编辑条目并自动保存',ui.summary.capture().promptBlocks[0].content==='下一次使用的规则');
  click('.tabs [data-tab="daily"]');await pause(40);check('其他助手页面显示总结状态',!q('[data-summary-global-status]').hidden);
  click('.tabs [data-tab="summary"]');await pause(40);check('切回面板保留已编辑条目与子页',q('.sa-tab-item.active').dataset.tab==='prompts'&&ui.summary.capture().promptBlocks[0].content==='下一次使用的规则');
  window.finishSummary('额外解释<summary_result>两人抵达城门。</summary_result>标签外检查');await pause(250);
  check('完成后按钮和自动隐藏开关恢复且关闭过的进度不弹成功提示',!q('#sa-start-summary').disabled&&!q('#sa-vis-auto-hide').disabled&&q('.sa-notice-layer').hidden);
  check('只保存标签内正文并隐藏对应楼层',Object.values(books).flat().some(e=>e.name==='总结0-19楼'&&e.content==='两人抵达城门。')&&messages.slice(0,20).every(m=>m.is_hidden)&&messages.slice(20).every(m=>!m.is_hidden));
  messages.push(...Array.from({length:20},(_,i)=>({message_id:i+30,role:'assistant',message:'<gametxt>后续 '+i+'</gametxt>',is_hidden:false})));
  click('#sa-start-summary');await pause(60);const callsBeforeStop=summaryCalls;
  click('[data-notice-stop]');await pause(60);check('停止仅取消本次总结请求',stopIds.at(-1)===lastRequest.generation_id&&q('[data-task-title]').textContent.includes('停止'));
  window.finishSummary('<summary_result>迟到结果</summary_result>');
  for(const handler of handlers.get('MESSAGE_RECEIVED')??[])handler();await pause(300);check('停止后的批次不会立即自动重启',summaryCalls===callsBeforeStop&&!Object.values(books).flat().some(e=>e.name==='总结20-39楼'));
  ui.closePanel();window.generateRaw=async()=>{throw Object.assign(Error('bad credentials https://example.invalid?key=private-secret'),{status:401});};
  click('[data-notice-retry]');await pause(150);check('失败提示可关闭且不自动打开面板',!ui.state.open&&!q('.dj-dialog')&&!q('.sa-notice-layer').hidden);
  click('.sa-notice-close');ui.openPanel();await pause(50);check('关闭失败提示后保留待处理入口',q('[data-task-title]').textContent.includes('认证失败')&&!q('[data-task-retry]').hidden);
  window.generateRaw=async request=>{lastRequest=request;const data={messages:request.ordered_prompts};for(const fn of handlers.get('CHAT_COMPLETION_SETTINGS_READY')??[])await fn(data);window.lastSentSummary=JSON.parse(JSON.stringify(data));return '<summary_result>恢复后的记录。</summary_result>';};
  click('[data-task-retry]');await pause(250);check('手动重试恢复完成并解除按钮锁定',!q('#sa-start-summary').disabled&&Object.values(books).flat().some(e=>e.name==='总结20-39楼'));
  check('实际发送请求已移除临时防合并标记',lastSentSummary.messages.every(p=>typeof p==='object'&&!p.content.includes('<|no-trans|>')));
  check('无独立总结窗口及全局旧样式',!document.querySelector('.sa-overlay')&&!document.querySelector('#sa-summary-hint-style'));
  return checks;
 })()`);
 console.log(results);fs.writeFileSync('.ui-review/assistant-test-results.json',JSON.stringify(results,null,2));
 await require('./summary-dialog-tests.cjs')(cdp,evaluate);
 await evaluate(`(async()=>{messages.push(...Array.from({length:20},(_,i)=>({message_id:i+50,role:'assistant',message:'<gametxt>布局 '+i+'</gametxt>',is_hidden:false})));window.generateRaw=request=>{lastRequest=request;return new Promise(resolve=>window.finishSummary=resolve);};ui.state.activeTab='summary';ui.render();ui.shadow.querySelector('#sa-start-summary').click();await new Promise(r=>setTimeout(r,70));})()`);
 for(const theme of ['midnight','forest','ember','parchment'])for(const width of [1280,390,320])for(const tab of ['status','settings','prompts','worldbook']){
  const height=width===1280?960:844;
  await cdp('Emulation.setDeviceMetricsOverride',{width,height,screenWidth:width,screenHeight:height,deviceScaleFactor:1,mobile:width<720});
  await evaluate(`ui.state.activeTab='settings';ui.render();var themeControl=ui.shadow.querySelector('[data-action="ui-theme"]');themeControl.value='${theme}';themeControl.dispatchEvent(new Event('change',{bubbles:true}));ui.state.activeTab='summary';ui.render();ui.shadow.querySelector('.sa-tab-item[data-tab="${tab}"]').click()`);
  const layout=await evaluate(`(()=>{const c=ui.shadow.querySelector('.content');return {overflow:c.scrollWidth>c.clientWidth+1,width:c.clientWidth,scroll:c.scrollWidth}})()`);assert(!layout.overflow,theme+' '+width+' '+tab+JSON.stringify(layout));
  if(tab==='status'){const image=await cdp('Page.captureScreenshot',{format:'png'});fs.writeFileSync('.ui-review/summary-'+theme+'-'+width+'.png',Buffer.from(image.data,'base64'));}
 }
 console.log('总结界面：4 主题 × 3 屏幕 × 4 子页布局通过');
};
